# Generated by Django 3.1.7 on 2021-03-28 21:21

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('assign_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('courier_type', models.CharField(blank=True, choices=[('foot', 'foot'), ('bike', 'bike'), ('car', 'car')], max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('courier_type', models.CharField(choices=[('foot', 'foot'), ('bike', 'bike'), ('car', 'car')], max_length=4)),
                ('regions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('working_hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), size=None)),
            ],
            managers=[
                ('add_funcs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('region', models.PositiveIntegerField()),
                ('delivery_hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), size=None)),
                ('complete_time', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.batch')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.courier'),
        ),
    ]
